const Joi = require("joi");
const mongoose = require("mongoose");
const schema = new mongoose.Schema({
  MarkAsRead: Boolean,
  Publish: Boolean,
  ShowAtHome: Boolean,
  Property: String,
  PropertyFor: String,
  Ptype: String,
  Utype: String,
  Address: String,
  Name: String,
  "Company Name": String,
  "Refrance Name": String,
  Designation: String,
  Email: String,
  State: String,
  District: String,
  City: String,
  Location: String,
  Floors: String,
  Facing: String,
  "Super Area": Number,
  "Carpet Area": Number,
  "Approx Area": Number,
  Budget: Number,
  Image: String,
  ImagePublicId: String,
  Having: String,
  Badrooms: String,
  Bathrooms: String,
  Balcony: String,
  "PG Name": String,
  "Refrance Person": String,
  "No of Rooms": String,
  "Single Sharing Rooms": String,
  "Double Sharing Rooms": String,
  "Triple Sharing Rooms": String,
  "Four Sharing Rooms": String,
  "Room Size": String,
  "Budget Only Rooms": Number,
  "Budget With All Meals": Number,
  "Hotel Name": String,
  "Hotel Type": String,
  "Restaurant Name": String,
  "Restaurant Type": String,
  Seatry: String,
  "Room Size": String,
  "Room Size": String,
  "Room Size": String,
  "Car Parking": Boolean,
  "Water 24hr": Boolean,
  "Police Station": Boolean,
  "Railway Station": Boolean,
  "Metro Station": Boolean,
  "Furnish Type": String,
  "Sky View": Boolean,
  "Pool View": Boolean,
  "Garden View": Boolean,
  "Parking View": Boolean,
  "Club House View": Boolean,
  "Main intrance Gate View": Boolean,
  "Outer Building View": Boolean,
  "Swiming Pool": Boolean,
  "Club House": Boolean,
  "Indoor Sports": Boolean,
  "Outdoor Sports": Boolean,
  Garden: Boolean,
  Temple: Boolean,
  "School:": Boolean,
  Hospital: Boolean,
  Gim: Boolean,
  Pool: Boolean,
  Sports: Boolean,
  Parking: Boolean,
  "Study Table": Boolean,
  Alram: Boolean,
  Locker: Boolean,
  Kitchen: Boolean,
  Bar: Boolean,
  "Banquet Hall": Boolean,
  Date: Date,
  "Available for": String
});
const schemaHeader = new mongoose.Schema({
  topId: Number,
  MarkAsRead: Boolean,
  Publish: Boolean,
  ShowAtHome: Boolean,
  Property: Boolean,
  PropertyFor: Boolean,
  Ptype: Boolean,
  Utype: Boolean,
  Address: Boolean,
  Name: Boolean,
  "Company Name": Boolean,
  "Refrance Name": Boolean,
  Designation: Boolean,
  Email: Boolean,
  State: Boolean,
  District: Boolean,
  City: Boolean,
  Location: Boolean,
  Floors: Boolean,
  Facing: Boolean,
  "Super Area": Boolean,
  "Carpet Area": Boolean,
  "Approx Area": Boolean,
  Budget: Boolean,
  Image: Boolean,
  Having: Boolean,
  Badrooms: Boolean,
  Bathrooms: Boolean,
  Balcony: Boolean,
  "PG Name": Boolean,
  "Refrance Person": Boolean,
  "No of Rooms": Boolean,
  "Single Sharing Rooms": Boolean,
  "Double Sharing Rooms": Boolean,
  "Triple Sharing Rooms": Boolean,
  "Four Sharing Rooms": Boolean,
  "Room Size": Boolean,
  "Budget Only Rooms": Boolean,
  "Budget With All Meals": Boolean,
  "Hotel Name": Boolean,
  "Hotel Type": Boolean,
  "Restaurant Name": Boolean,
  "Restaurant Type": Boolean,
  Seatry: Boolean,
  "Car Parking": Boolean,
  "Water 24hr": Boolean,
  "Police Station": Boolean,
  "Railway Station": Boolean,
  "Metro Station": Boolean,
  "Furnish Type": Boolean,
  "Sky View": Boolean,
  "Pool View": Boolean,
  "Garden View": Boolean,
  "Parking View": Boolean,
  "Club House View": Boolean,
  "Main intrance Gate View": Boolean,
  "Outer Building View": Boolean,
  "Swiming Pool": Boolean,
  "Club House": Boolean,
  "Indoor Sports": Boolean,
  "Outdoor Sports": Boolean,
  Garden: Boolean,
  Temple: Boolean,
  "School:": Boolean,
  Hospital: Boolean,
  Gim: Boolean,
  Pool: Boolean,
  Sports: Boolean,
  Parking: Boolean,
  "Study Table": Boolean,
  Alram: Boolean,
  Locker: Boolean,
  Kitchen: Boolean,
  Bar: Boolean,
  "Banquet Hall": Boolean,
  Date: Boolean,
  "Available for": Boolean
});
const Property = mongoose.model("Property", schema);
const Header = mongoose.model("Header", schemaHeader);

function validateCustomer(customer) {
  const schema = {
    name: Joi.string()
      .min(5)
      .max(50)
      .required(),
    phone: Joi.string()
      .min(5)
      .max(50)
      .required(),
    isGold: Joi.boolean()
  };

  return Joi.validate(customer, schema);
}

exports.Property = Property;
exports.Header = Header;
exports.validate = validateCustomer;
